version: '3.9'

services:
  db:
    image: postgres:15.1-alpine
    restart: always
    container_name: postgres_db
    environment:
      - PGUSER=${DB_USER}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${API_PORT}:8000
    volumes:
      - .:/app
    command: bash -c 'uvicorn main:app --host ${API_HOST} --port ${API_PORT}'
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres-data:
